// <auto-generated />
using System;
using Infrastructure.Database.Context;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Vitalitas.Infrastructure.Database.Migrations
{
    [DbContext(typeof(VitalitasDbContext))]
    [Migration("20260728144826_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.9")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Domain.Features.Academia.Entities.Academia", b =>
                {
                    b.Property<Guid>("IdAcademia")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Bairro")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("CEP")
                        .IsRequired()
                        .HasMaxLength(8)
                        .HasColumnType("nvarchar(8)");

                    b.Property<string>("CNPJ")
                        .IsRequired()
                        .HasMaxLength(14)
                        .HasColumnType("nvarchar(14)");

                    b.Property<string>("Cidade")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("EmailInstitucional")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Estado")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<Guid>("IdGestor")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("IdLicenca")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("NomeAcademia")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Quadra")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Rua")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<int>("TipoAcademia")
                        .HasColumnType("int");

                    b.HasKey("IdAcademia");

                    b.ToTable("Academias");
                });

            modelBuilder.Entity("Domain.Features.Academia.Entities.TelefoneAcademia", b =>
                {
                    b.Property<Guid>("IdTelefone")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("IdAcademia")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Telefone")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.HasKey("IdTelefone");

                    b.ToTable("TelefonesAcademia");
                });

            modelBuilder.Entity("Domain.Features.Fichas.Ficha.Entities.Ficha", b =>
                {
                    b.Property<Guid>("IdFicha")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("IdAcademia")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("IdAvaliacao")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("NomeFicha")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Observacoes")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.HasKey("IdFicha");

                    b.HasIndex("IdAcademia", "IdFicha");

                    b.ToTable("Fichas");
                });

            modelBuilder.Entity("Domain.Features.Fichas.FichaMedica.Entities.FichaMedica", b =>
                {
                    b.Property<Guid>("IdFicha")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Alergia")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Cirurgia")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<Guid>("IdAcademia")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("IdAluno")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Lesao")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<string>("ProblemaSaude")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<string>("Restricao")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<string>("UsoMedicamento")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.HasKey("IdFicha");

                    b.HasIndex("IdAluno");

                    b.HasIndex("IdAcademia", "IdFicha");

                    b.ToTable("FichasMedicas");
                });

            modelBuilder.Entity("Domain.Features.Planos.Contrato.Entities.Contrato", b =>
                {
                    b.Property<Guid>("IdContrato")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateOnly>("DataAssinatura")
                        .HasColumnType("date");

                    b.Property<DateOnly>("DataFim")
                        .HasColumnType("date");

                    b.Property<Guid>("IdPlanoContrato")
                        .HasColumnType("uniqueidentifier");

                    b.Property<decimal>("Mensalidade")
                        .HasColumnType("decimal(10,2)");

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.HasKey("IdContrato");

                    b.ToTable("Contratos");
                });

            modelBuilder.Entity("Domain.Features.Planos.Contrato.Entities.PlanoContrato", b =>
                {
                    b.Property<Guid>("IdPlano")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Descricao")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<decimal>("Valor")
                        .HasColumnType("decimal(10,2)");

                    b.HasKey("IdPlano");

                    b.ToTable("PlanosContrato");
                });

            modelBuilder.Entity("Domain.Features.Planos.Licenca.Entities.Licenca", b =>
                {
                    b.Property<Guid>("IdLicenca")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("CaminhoPdf")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<DateOnly>("DataFim")
                        .HasColumnType("date");

                    b.Property<DateOnly>("DateAssinatura")
                        .HasColumnType("date");

                    b.Property<Guid>("IdPlano")
                        .HasColumnType("uniqueidentifier");

                    b.Property<decimal>("Mensalidade")
                        .HasColumnType("decimal(10,2)");

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.Property<int>("Tipo")
                        .HasColumnType("int");

                    b.HasKey("IdLicenca");

                    b.ToTable("Licencas");
                });

            modelBuilder.Entity("Domain.Features.Planos.Licenca.Entities.PlanoLicenca", b =>
                {
                    b.Property<Guid>("IdPlanoLicenca")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Descricao")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<decimal>("Valor")
                        .HasColumnType("decimal(10,2)");

                    b.HasKey("IdPlanoLicenca");

                    b.ToTable("PlanosLicenca");
                });

            modelBuilder.Entity("Domain.Features.Shared.Entities.Agenda", b =>
                {
                    b.Property<Guid>("IdAgenda")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("Data")
                        .HasColumnType("datetime2");

                    b.Property<Guid>("IdAcademia")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("IdInstrutor")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.HasKey("IdAgenda");

                    b.HasIndex("IdAcademia", "IdAgenda");

                    b.ToTable("Agendas");
                });

            modelBuilder.Entity("Domain.Features.Shared.Entities.Avaliacao", b =>
                {
                    b.Property<Guid>("IdAvaliacao")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<double>("Ab")
                        .HasColumnType("float");

                    b.Property<double>("Abdomen")
                        .HasColumnType("float");

                    b.Property<double>("Altura")
                        .HasColumnType("float");

                    b.Property<double>("Ax")
                        .HasColumnType("float");

                    b.Property<double>("BracoD")
                        .HasColumnType("float");

                    b.Property<double>("BracoE")
                        .HasColumnType("float");

                    b.Property<double>("CoxaD")
                        .HasColumnType("float");

                    b.Property<double>("CoxaE")
                        .HasColumnType("float");

                    b.Property<DateOnly>("Data")
                        .HasColumnType("date");

                    b.Property<double>("Deltoide")
                        .HasColumnType("float");

                    b.Property<double>("Densidade")
                        .HasColumnType("float");

                    b.Property<double>("Femur")
                        .HasColumnType("float");

                    b.Property<double>("Glicemia")
                        .HasColumnType("float");

                    b.Property<TimeOnly>("Hora")
                        .HasColumnType("time");

                    b.Property<Guid>("IdAcademia")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("IdAluno")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("IdProfessor")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("Idade")
                        .HasColumnType("int");

                    b.Property<double>("PGordo")
                        .HasColumnType("float");

                    b.Property<double>("PMagro")
                        .HasColumnType("float");

                    b.Property<double>("POsseo")
                        .HasColumnType("float");

                    b.Property<double>("PViscera")
                        .HasColumnType("float");

                    b.Property<string>("Pa")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<double>("Peitoral")
                        .HasColumnType("float");

                    b.Property<double>("PernaD")
                        .HasColumnType("float");

                    b.Property<double>("PernaE")
                        .HasColumnType("float");

                    b.Property<double>("Peso")
                        .HasColumnType("float");

                    b.Property<double>("Pr")
                        .HasColumnType("float");

                    b.Property<double>("Pt")
                        .HasColumnType("float");

                    b.Property<double>("Px")
                        .HasColumnType("float");

                    b.Property<double>("Quadril")
                        .HasColumnType("float");

                    b.Property<double>("Rt")
                        .HasColumnType("float");

                    b.Property<double>("Se")
                        .HasColumnType("float");

                    b.Property<string>("Sexo")
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)");

                    b.Property<double>("Si")
                        .HasColumnType("float");

                    b.Property<double>("Torax")
                        .HasColumnType("float");

                    b.Property<double>("Tr")
                        .HasColumnType("float");

                    b.Property<double>("Ub")
                        .HasColumnType("float");

                    b.Property<double>("Ur")
                        .HasColumnType("float");

                    b.HasKey("IdAvaliacao");

                    b.HasIndex("IdAcademia", "IdAvaliacao");

                    b.ToTable("Avaliacoes");
                });

            modelBuilder.Entity("Domain.Features.Shared.Entities.LogAtividade", b =>
                {
                    b.Property<Guid>("IdLog")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("Acao")
                        .HasColumnType("int");

                    b.Property<DateTime>("DataHora")
                        .HasColumnType("datetime2");

                    b.Property<string>("DispositivoLogado")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<Guid>("IdAcademia")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("IdUsuario")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Localizacao")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.HasKey("IdLog");

                    b.HasIndex("IdUsuario");

                    b.HasIndex("IdAcademia", "IdLog");

                    b.ToTable("LogsAtividade");
                });

            modelBuilder.Entity("Domain.Features.Shared.Entities.Treino", b =>
                {
                    b.Property<Guid>("IdTreino")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Exercicio")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid>("IdAcademia")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("IdFicha")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("NomeTreino")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<int>("Tipo")
                        .HasColumnType("int");

                    b.HasKey("IdTreino");

                    b.HasIndex("IdAcademia", "IdTreino");

                    b.ToTable("Treinos");
                });

            modelBuilder.Entity("Domain.Features.Token.Entities.RefreshToken", b =>
                {
                    b.Property<Guid>("IdRefreshToken")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("DataExpiracao")
                        .HasColumnType("datetime2");

                    b.Property<Guid>("IdAcademia")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("IdUsuario")
                        .HasColumnType("uniqueidentifier");

                    b.Property<bool>("Revogado")
                        .HasColumnType("bit");

                    b.Property<string>("TokenHash")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.HasKey("IdRefreshToken");

                    b.HasIndex("IdUsuario");

                    b.HasIndex("TokenHash");

                    b.HasIndex("IdAcademia", "IdRefreshToken");

                    b.ToTable("RefreshTokens");
                });

            modelBuilder.Entity("Domain.Features.Usuarios.Administrador.Entities.Administrador", b =>
                {
                    b.Property<Guid>("IdFuncionario")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("Cargo")
                        .HasColumnType("int");

                    b.Property<Guid>("IdAcademia")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("IdUsuario")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("IdFuncionario");

                    b.HasIndex("IdAcademia", "IdFuncionario");

                    b.ToTable("Administradores");
                });

            modelBuilder.Entity("Domain.Features.Usuarios.Aluno.Entities.Aluno", b =>
                {
                    b.Property<Guid>("IdAluno")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("IdAcademia")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("IdContrato")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("IdInstrutor")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("IdUsuario")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Objetivo")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.HasKey("IdAluno");

                    b.HasIndex("IdInstrutor");

                    b.HasIndex("IdUsuario");

                    b.HasIndex("IdAcademia", "IdAluno");

                    b.ToTable("Alunos");
                });

            modelBuilder.Entity("Domain.Features.Usuarios.Aluno.Entities.Frequencia", b =>
                {
                    b.Property<Guid>("IdFrequencia")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("Data")
                        .HasColumnType("datetime2");

                    b.Property<Guid>("IdAcademia")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("IdAluno")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("TempoTreinoMinutos")
                        .HasColumnType("int");

                    b.HasKey("IdFrequencia");

                    b.HasIndex("IdAluno");

                    b.HasIndex("IdAcademia", "IdFrequencia");

                    b.ToTable("Frequencias");
                });

            modelBuilder.Entity("Domain.Features.Usuarios.Aluno.Entities.XpHistorico", b =>
                {
                    b.Property<Guid>("IdXp")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("Data")
                        .HasColumnType("datetime2");

                    b.Property<Guid>("IdAcademia")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("IdUsuario")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Motivo")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<int>("XpGanho")
                        .HasColumnType("int");

                    b.HasKey("IdXp");

                    b.HasIndex("IdUsuario");

                    b.HasIndex("IdAcademia", "IdXp");

                    b.ToTable("XpHistoricos");
                });

            modelBuilder.Entity("Domain.Features.Usuarios.Common.Entities.TelefoneUsuario", b =>
                {
                    b.Property<Guid>("IdTelefone")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("IdAcademia")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("IdUsuario")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Telefone")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.HasKey("IdTelefone");

                    b.HasIndex("IdAcademia", "IdTelefone");

                    b.ToTable("TelefonesUsuario");
                });

            modelBuilder.Entity("Domain.Features.Usuarios.Common.Entities.Usuario", b =>
                {
                    b.Property<Guid>("IdUsuario")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<bool>("Ativo")
                        .HasColumnType("bit");

                    b.Property<string>("Bairro")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("CEP")
                        .IsRequired()
                        .HasMaxLength(8)
                        .HasColumnType("nvarchar(8)");

                    b.Property<string>("CPF")
                        .IsRequired()
                        .HasMaxLength(11)
                        .HasColumnType("nvarchar(11)");

                    b.Property<string>("Cidade")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<DateOnly>("DataNascimento")
                        .HasColumnType("date");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Estado")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<bool>("Flag")
                        .HasColumnType("bit");

                    b.Property<Guid>("IdAcademia")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Quadra")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Rua")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Senha")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<int>("TipoUsuario")
                        .HasColumnType("int");

                    b.HasKey("IdUsuario");

                    b.HasIndex("CPF")
                        .IsUnique();

                    b.HasIndex("Email")
                        .IsUnique();

                    b.HasIndex("IdAcademia", "IdUsuario");

                    b.ToTable("Usuarios");
                });

            modelBuilder.Entity("Domain.Features.Usuarios.Funcionario.Entities.Funcionario", b =>
                {
                    b.Property<Guid>("IdFuncionario")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("Cargo")
                        .HasColumnType("int");

                    b.Property<Guid>("IdAcademia")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("IdUsuario")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("IdFuncionario");

                    b.HasIndex("IdUsuario");

                    b.HasIndex("IdAcademia", "IdFuncionario");

                    b.ToTable("Funcionarios");
                });

            modelBuilder.Entity("Domain.Features.Usuarios.Gestor.Entities.Gestor", b =>
                {
                    b.Property<Guid>("IdGestor")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("IdAcademia")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("IdUsuario")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("IdGestor");

                    b.HasIndex("IdUsuario");

                    b.HasIndex("IdAcademia", "IdGestor");

                    b.ToTable("Gestores");
                });

            modelBuilder.Entity("Domain.Features.Usuarios.Instrutor.Entities.Instrutor", b =>
                {
                    b.Property<Guid>("IdInstrutor")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("CREF")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)");

                    b.Property<Guid>("IdAcademia")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("IdUsuario")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("IdInstrutor");

                    b.HasIndex("IdUsuario");

                    b.HasIndex("IdAcademia", "IdInstrutor");

                    b.ToTable("Instrutores");
                });
#pragma warning restore 612, 618
        }
    }
}
