// <auto-generated />
using System;
using Infrastructure.Database.Context;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Infrastructure.Database.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260807112226_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.18")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Domain.Features.Gym.Entities.Gym", b =>
                {
                    b.Property<Guid>("IdAcadenia")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Bairro")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("Bairro");

                    b.Property<string>("CEP")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("CEP");

                    b.Property<string>("CNPJ")
                        .IsRequired()
                        .HasMaxLength(18)
                        .HasColumnType("nvarchar(18)")
                        .HasColumnName("CNPJ");

                    b.Property<string>("Cidade")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("Cidade");

                    b.Property<string>("EmailInstitucional")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)")
                        .HasColumnName("EmailInstitucional");

                    b.Property<string>("Estado")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("Estado");

                    b.Property<Guid>("IdGestor")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("IdLicenca")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("NomeAcademia")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)")
                        .HasColumnName("NomeAcademia");

                    b.Property<string>("Quadra")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("Quadra");

                    b.Property<string>("Rua")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("Rua");

                    b.Property<int>("GymType")
                        .HasColumnType("int")
                        .HasColumnName("GymType");

                    b.HasKey("IdAcadenia");

                    b.ToTable("Gym", (string)null);
                });

            modelBuilder.Entity("Domain.Features.Gym.Entities.GymPhone", b =>
                {
                    b.Property<Guid>("IdTelefone")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("IdAcademia")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Telefone")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)")
                        .HasColumnName("Telefone");

                    b.HasKey("IdTelefone");

                    b.ToTable("GymPhone", (string)null);
                });

            modelBuilder.Entity("Domain.Features.Records.TrainingSheet.Entities.TrainingSheet", b =>
                {
                    b.Property<Guid>("IdFicha")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("IdAvaliacao")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("NomeFicha")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)")
                        .HasColumnName("NomeFicha");

                    b.Property<string>("Observacoes")
                        .IsRequired()
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)")
                        .HasColumnName("Observacoes");

                    b.HasKey("IdFicha");

                    b.ToTable("TrainingSheet", (string)null);
                });

            modelBuilder.Entity("Domain.Features.Records.MedicalRecord.Entities.MedicalRecord", b =>
                {
                    b.Property<Guid>("IdFicha")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Alergia")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)")
                        .HasColumnName("Alergia");

                    b.Property<string>("Cirurgia")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)")
                        .HasColumnName("Cirurgia");

                    b.Property<Guid>("IdAluno")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Lesao")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)")
                        .HasColumnName("Lesao");

                    b.Property<string>("ProblemaSaude")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)")
                        .HasColumnName("ProblemaSaude");

                    b.Property<string>("Restricao")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)")
                        .HasColumnName("Restricao");

                    b.Property<string>("UsoMedicamento")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)")
                        .HasColumnName("UsoMedicamento");

                    b.HasKey("IdFicha");

                    b.ToTable("MedicalRecord", (string)null);
                });

            modelBuilder.Entity("Domain.Features.Plans.Contract.Entities.Contract", b =>
                {
                    b.Property<Guid>("IdContrato")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateOnly>("DataAssinatura")
                        .HasColumnType("date")
                        .HasColumnName("DataAssinatura");

                    b.Property<DateOnly>("DataFim")
                        .HasColumnType("date")
                        .HasColumnName("DataFim");

                    b.Property<Guid>("IdPlanoContrato")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Mensalidade")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)")
                        .HasColumnName("Mensalidade");

                    b.Property<int>("Status")
                        .HasColumnType("int")
                        .HasColumnName("Status");

                    b.HasKey("IdContrato");

                    b.ToTable("Contract", (string)null);
                });

            modelBuilder.Entity("Domain.Features.Plans.Contract.Entities.ContractPlan", b =>
                {
                    b.Property<Guid>("IdPlano")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Descricao")
                        .IsRequired()
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)")
                        .HasColumnName("Descricao");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)")
                        .HasColumnName("Name");

                    b.Property<string>("Valor")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)")
                        .HasColumnName("Valor");

                    b.HasKey("IdPlano");

                    b.ToTable("ContractPlan", (string)null);
                });

            modelBuilder.Entity("Domain.Features.Plans.License.Entities.License", b =>
                {
                    b.Property<Guid>("IdLicenca")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("CaminhoPdf")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)")
                        .HasColumnName("CaminhoPdf");

                    b.Property<DateOnly>("DataFim")
                        .HasColumnType("date")
                        .HasColumnName("DataFim");

                    b.Property<DateOnly>("DateAssinatura")
                        .HasColumnType("date")
                        .HasColumnName("DataAssinatura");

                    b.Property<Guid>("IdPlano")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Mensalidade")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)")
                        .HasColumnName("Mensalidade");

                    b.Property<int>("Status")
                        .HasColumnType("int")
                        .HasColumnName("Status");

                    b.Property<int>("Tipo")
                        .HasColumnType("int")
                        .HasColumnName("Tipo");

                    b.HasKey("IdLicenca");

                    b.ToTable("License", (string)null);
                });

            modelBuilder.Entity("Domain.Features.Plans.License.Entities.LicensePlan", b =>
                {
                    b.Property<Guid>("IdPlanoLicenca")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Descricao")
                        .IsRequired()
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)")
                        .HasColumnName("Descricao");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)")
                        .HasColumnName("Name");

                    b.Property<string>("Valor")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)")
                        .HasColumnName("Valor");

                    b.HasKey("IdPlanoLicenca");

                    b.ToTable("LicensePlan", (string)null);
                });

            modelBuilder.Entity("Domain.Features.Shared.Entities.Schedule", b =>
                {
                    b.Property<int>("IdAgenda")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdAgenda"));

                    b.Property<DateTime>("Data")
                        .HasColumnType("datetime2")
                        .HasColumnName("Data");

                    b.Property<Guid>("IdAcademia")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("IdInstrutor")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("Status")
                        .HasColumnType("int")
                        .HasColumnName("Status");

                    b.HasKey("IdAgenda");

                    b.ToTable("Schedule", (string)null);
                });

            modelBuilder.Entity("Domain.Features.Shared.Entities.Avaliacao", b =>
                {
                    b.Property<int>("IdAvaliacao")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id_avaliacao");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdAvaliacao"));

                    b.Property<double>("Ab")
                        .HasColumnType("float")
                        .HasColumnName("ab");

                    b.Property<double>("Abdomen")
                        .HasColumnType("float")
                        .HasColumnName("abdomen");

                    b.Property<double>("Altura")
                        .HasColumnType("float")
                        .HasColumnName("altura");

                    b.Property<double>("Ax")
                        .HasColumnType("float")
                        .HasColumnName("ax");

                    b.Property<double>("BracoD")
                        .HasColumnType("float")
                        .HasColumnName("braco_d");

                    b.Property<double>("BracoE")
                        .HasColumnType("float")
                        .HasColumnName("braco_e");

                    b.Property<double>("CoxaD")
                        .HasColumnType("float")
                        .HasColumnName("coxa_d");

                    b.Property<double>("CoxaE")
                        .HasColumnType("float")
                        .HasColumnName("coxa_e");

                    b.Property<DateOnly>("Data")
                        .HasColumnType("date")
                        .HasColumnName("data");

                    b.Property<double>("Deltoide")
                        .HasColumnType("float")
                        .HasColumnName("deltoide");

                    b.Property<double>("Densidade")
                        .HasColumnType("float")
                        .HasColumnName("densidade");

                    b.Property<double>("Femur")
                        .HasColumnType("float")
                        .HasColumnName("femur");

                    b.Property<double>("Glicemia")
                        .HasColumnType("float")
                        .HasColumnName("glicemia");

                    b.Property<TimeOnly>("Hora")
                        .HasColumnType("time")
                        .HasColumnName("hora");

                    b.Property<int>("IdAluno")
                        .HasColumnType("int")
                        .HasColumnName("id_aluno");

                    b.Property<int>("IdProfessor")
                        .HasColumnType("int")
                        .HasColumnName("id_professor");

                    b.Property<int>("Idade")
                        .HasColumnType("int")
                        .HasColumnName("idade");

                    b.Property<double>("PGordo")
                        .HasColumnType("float")
                        .HasColumnName("p_gordo");

                    b.Property<double>("PMagro")
                        .HasColumnType("float")
                        .HasColumnName("p_magro");

                    b.Property<double>("POsseo")
                        .HasColumnType("float")
                        .HasColumnName("p_osseo");

                    b.Property<double>("PViscera")
                        .HasColumnType("float")
                        .HasColumnName("p_viscera");

                    b.Property<string>("Pa")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("pa");

                    b.Property<double>("Peitoral")
                        .HasColumnType("float")
                        .HasColumnName("peitoral");

                    b.Property<double>("PernaD")
                        .HasColumnType("float")
                        .HasColumnName("perna_d");

                    b.Property<double>("PernaE")
                        .HasColumnType("float")
                        .HasColumnName("perna_e");

                    b.Property<double>("Peso")
                        .HasColumnType("float")
                        .HasColumnName("peso");

                    b.Property<double>("Pr")
                        .HasColumnType("float")
                        .HasColumnName("pr");

                    b.Property<double>("Pt")
                        .HasColumnType("float")
                        .HasColumnName("pt");

                    b.Property<double>("Px")
                        .HasColumnType("float")
                        .HasColumnName("px");

                    b.Property<double>("Quadril")
                        .HasColumnType("float")
                        .HasColumnName("quadril");

                    b.Property<double>("Rt")
                        .HasColumnType("float")
                        .HasColumnName("rt");

                    b.Property<double>("Se")
                        .HasColumnType("float")
                        .HasColumnName("se");

                    b.Property<string>("Sexo")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("sexo");

                    b.Property<double>("Si")
                        .HasColumnType("float")
                        .HasColumnName("si");

                    b.Property<double>("Torax")
                        .HasColumnType("float")
                        .HasColumnName("torax");

                    b.Property<double>("Tr")
                        .HasColumnType("float")
                        .HasColumnName("tr");

                    b.Property<double>("Ub")
                        .HasColumnType("float")
                        .HasColumnName("ub");

                    b.Property<double>("Ur")
                        .HasColumnType("float")
                        .HasColumnName("ur");

                    b.HasKey("IdAvaliacao");

                    b.ToTable("avaliacao");
                });

            modelBuilder.Entity("Domain.Features.Shared.Entities.ActivityLog", b =>
                {
                    b.Property<Guid>("IdLog")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("Acao")
                        .HasColumnType("int")
                        .HasColumnName("Acao");

                    b.Property<DateTime>("DataHora")
                        .HasColumnType("datetime2")
                        .HasColumnName("DataHora");

                    b.Property<string>("DispositivoLogado")
                        .IsRequired()
                        .HasMaxLength(300)
                        .HasColumnType("nvarchar(300)")
                        .HasColumnName("DispositivoLogado");

                    b.Property<Guid>("IdUsuario")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Localizacao")
                        .IsRequired()
                        .HasMaxLength(300)
                        .HasColumnType("nvarchar(300)")
                        .HasColumnName("Localizacao");

                    b.HasKey("IdLog");

                    b.ToTable("ActivityLog", (string)null);
                });

            modelBuilder.Entity("Domain.Features.Shared.Entities.Workout", b =>
                {
                    b.Property<Guid>("IdTreino")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Exercise")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("Exercise");

                    b.Property<Guid>("IdFicha")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("NomeTreino")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)")
                        .HasColumnName("NomeTreino");

                    b.Property<int>("Tipo")
                        .HasColumnType("int")
                        .HasColumnName("Tipo");

                    b.HasKey("IdTreino");

                    b.ToTable("Workout", (string)null);
                });

            modelBuilder.Entity("Domain.Features.Token.Entities.RefreshToken", b =>
                {
                    b.Property<Guid>("IdRefreshToken")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("DataExpiracao")
                        .HasColumnType("datetime2")
                        .HasColumnName("DataExpiracao");

                    b.Property<Guid>("IdUsuario")
                        .HasColumnType("uniqueidentifier");

                    b.Property<bool>("Revogado")
                        .HasColumnType("bit")
                        .HasColumnName("Revogado");

                    b.Property<string>("TokenHash")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)")
                        .HasColumnName("TokenHash");

                    b.HasKey("IdRefreshToken");

                    b.ToTable("RefreshToken", (string)null);
                });

            modelBuilder.Entity("Domain.Features.Users.Administrator.Entities.Administrator", b =>
                {
                    b.Property<Guid>("IdFuncionario")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("Role")
                        .HasColumnType("int")
                        .HasColumnName("Role");

                    b.Property<Guid>("IdUsuario")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("IdFuncionario");

                    b.ToTable("Administrator", (string)null);
                });

            modelBuilder.Entity("Domain.Features.Users.Member.Entities.Member", b =>
                {
                    b.Property<Guid>("IdAluno")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("IdContrato")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("IdInstrutor")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("IdUsuario")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Goal")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)")
                        .HasColumnName("Goal");

                    b.HasKey("IdAluno");

                    b.ToTable("Member", (string)null);
                });

            modelBuilder.Entity("Domain.Features.Users.Member.Entities.Attendance", b =>
                {
                    b.Property<Guid>("IdFrequencia")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("Data")
                        .HasColumnType("datetime2")
                        .HasColumnName("Data");

                    b.Property<Guid>("IdAluno")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("TempoTreinoMinutos")
                        .HasColumnType("int")
                        .HasColumnName("TempoTreinoMinutos");

                    b.HasKey("IdFrequencia");

                    b.ToTable("Attendance", (string)null);
                });

            modelBuilder.Entity("Domain.Features.Users.Member.Entities.XpHistory", b =>
                {
                    b.Property<Guid>("IdXp")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("Data")
                        .HasColumnType("datetime2")
                        .HasColumnName("Data");

                    b.Property<Guid>("IdUsuario")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Motivo")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)")
                        .HasColumnName("Motivo");

                    b.Property<int>("XpGanho")
                        .HasColumnType("int")
                        .HasColumnName("XpGanho");

                    b.HasKey("IdXp");

                    b.ToTable("XpHistory", (string)null);
                });

            modelBuilder.Entity("Domain.Features.Users.Common.Entities.UserPhone", b =>
                {
                    b.Property<Guid>("IdTelefone")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("IdUsuario")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Telefone")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)")
                        .HasColumnName("Telefone");

                    b.HasKey("IdTelefone");

                    b.ToTable("UserPhone", (string)null);
                });

            modelBuilder.Entity("Domain.Features.Users.Common.Entities.User", b =>
                {
                    b.Property<Guid>("IdUsuario")
                        .HasColumnType("uniqueidentifier");

                    b.Property<bool>("Ativo")
                        .HasColumnType("bit")
                        .HasColumnName("Ativo");

                    b.Property<string>("Bairro")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("Bairro");

                    b.Property<string>("CEP")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("CEP");

                    b.Property<string>("CPF")
                        .IsRequired()
                        .HasMaxLength(14)
                        .HasColumnType("nvarchar(14)")
                        .HasColumnName("CPF");

                    b.Property<string>("Cidade")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("Cidade");

                    b.Property<DateOnly>("DataNascimento")
                        .HasColumnType("date")
                        .HasColumnName("DataNascimento");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)")
                        .HasColumnName("Email");

                    b.Property<string>("Estado")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("Estado");

                    b.Property<bool>("Flag")
                        .HasColumnType("bit")
                        .HasColumnName("Flag");

                    b.Property<Guid>("IdAcademia")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)")
                        .HasColumnName("Name");

                    b.Property<string>("Quadra")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("Quadra");

                    b.Property<string>("Rua")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("Rua");

                    b.Property<string>("Senha")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("Senha");

                    b.Property<int>("UserType")
                        .HasColumnType("int")
                        .HasColumnName("UserType");

                    b.HasKey("IdUsuario");

                    b.ToTable("User", (string)null);
                });

            modelBuilder.Entity("Domain.Features.Users.Employee.Entities.Employee", b =>
                {
                    b.Property<Guid>("IdFuncionario")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("Role")
                        .HasColumnType("int")
                        .HasColumnName("Role");

                    b.Property<Guid>("IdUsuario")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("IdFuncionario");

                    b.ToTable("Employee", (string)null);
                });

            modelBuilder.Entity("Domain.Features.Users.Manager.Entities.Manager", b =>
                {
                    b.Property<Guid>("IdGestor")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("IdUsuario")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("IdGestor");

                    b.ToTable("Manager", (string)null);
                });

            modelBuilder.Entity("Domain.Features.Users.Instructor.Entities.Instructor", b =>
                {
                    b.Property<Guid>("IdInstrutor")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("CREF")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)")
                        .HasColumnName("CREF");

                    b.Property<Guid>("IdUsuario")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("IdInstrutor");

                    b.ToTable("Instructor", (string)null);
                });
#pragma warning restore 612, 618
        }
    }
}
